export const texts = [
	`Fog everywhere. Fog up the river, where it flows among green aits and meadows; fog down the river, where it rolls deified among the tiers of shipping and the waterside pollutions of a great (and dirty) city. Fog on the Essex marshes, fog on the Kentish heights. Fog creeping into the cabooses of collier-brigs; fog lying out on the yards and hovering in the rigging of great ships; fog drooping on the gunwales of barges and small boats.`,
	`Fog in the eyes and throats of ancient Greenwich pensioners, wheezing by the firesides of their wards; fog in the stem and bowl of the afternoon pipe of the wrathful skipper, down in his close cabin; fog cruelly pinching the toes and fingers of his shivering little 'prentice boy on deck. Chance people on the bridges peeping over the parapets into a nether sky of fog, with fog all round them, as if they were up in a balloon, and hanging in the misty clouds.`,
	`The raw afternoon is rawest, and the dense fog is densest, and the muddy streets are muddiest near that leaden-headed old obstruction, appropriate ornament for the threshold of a leaden-headed old corporation, Temple Bar. And hard by Temple Bar, in Lincoln's Inn Hall, at the very heart of the fog, sits the Lord High Chancellor in his High Court of Chancery.`,
	`Never can there come fog too thick, never can there come mud and mire too deep, to assort with the groping and floundering condition which this High Court of Chancery, most pestilent of hoary sinners, holds this day in the sight of heaven and earth.`,
	`On such an afternoon the various solicitors in the cause, some two or three of whom have inherited it from their fathers, who made a fortune by it, ought to be—as are they not?—ranged in a line, in a long matted well (but you might look in vain for truth at the bottom of it) between the registrar's red table and the silk gowns, with bills, cross-bills, answers, rejoinders, injunctions, affidavits, issues, references to masters, masters' reports, mountains of costly nonsense, piled before them.`,
	`And Eurypylus, son of Euaemon, killed Hypsenor, the son of noble Dolopion, who had been made priest of the river Scamander, and was honoured among the people as though he were a god. Eurypylus gave him chase as he was flying before him, smote him with his sword upon the arm, and lopped his strong hand from off it. The bloody hand fell to the ground, and the shades of death, with fate that no man can withstand, came over his eyes. Thus furiously did the battle rage between them.`,
	`As for the son of Tydeus, you could not say whether he was more among the Achaeans or the Trojans. He rushed across the plain like a winter torrent that has burst its barrier in full flood; no dykes, no walls of fruitful vineyards can embank it when it is swollen with rain from heaven, but in a moment it comes tearing onward, and lays many a field waste that many a strong man hand has reclaimed- even so were the dense phalanxes of the Trojans driven in rout by the son of Tydeus, and many though they were, they dared not abide his onslaught.`,
	`His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.`,
	`Debbie knew she was being selfish and unreasonable. She understood why the others in the room were angry and frustrated with her and the way she was acting. In her eyes, it didn't really matter how they felt because she simply didn't care.`,
	`There was no time. He ran out of the door without half the stuff he needed for work, but it didn't matter. He was late and if he didn't make this meeting on time, someone's life may be in danger.`,
	`Twenty-five years Dana had been waiting. She tried to be patient during that time but she hadn't always managed to be as patient as she'd like. But today the opportunity had finally come. The thing she always imagined would make her the happiest person in the world was about to happen. She didn't know why at this specific time she all of a sudden felt sick inside.`,
	`The shades were closed keeping the room dark. Peter knew that he should open them and let in the sunlight so he could begin the day, but he didn't have the energy or willpower. Nothing had gone as expected the day before and he no longer wanted to spend the energy to begin a new day. He stared at the shades wondering if there was a way to disappear from the reality of the world for the rest of the day.`,
	`He took a sip of the drink. He wasn't sure whether he liked it or not, but at this moment it didn't matter. She had made it especially for him so he would have forced it down even if he had absolutely hated it. That's simply the way things worked. She made him a new-fangled drink each day and he took a sip of it and smiled, saying it was excellent.`,
	`There was a reason for her shyness. Everyone assumed it had always been there but she knew better. She knew the exact moment that the shyness began. It had been that fateful moment at the lake. There are just some events that do that to you.`,
	`The young man wanted a role model. He looked long and hard in his youth, but that role model never materialized. His only choice was to embrace all the people in his life he didn't want to be like.`,
	`April seriously wondered about her sleeping partner choices. She looked at her bed and what a mess it had become. How did she get to the point in her life where she had two dogs, three cats, and a raccoon sleeping with her every night?`,
	`It all started with a random letter. Several of those were joined forces to create a random word. The words decided to get together and form a random sentence. They decided not to stop there and it wasn't long before a random paragraph had been cobbled together. The question was whether or not they could continue the momentum long enough to create a random short story.`,
	`There is a time and place for everything, and I love a good random sentence as much as the next guy, but this is just nonsense. I mean, really, who ever heard of a random paragraph? It just doesn't make sense. Just when you think you have seen it all, you get a random letter thrown into the mix. I think I've had about enough of this random word stuff for one day.`,
	`I am a very random person. I can think of random stuff all day long. Sometimes I just can't stop. Random words are always popping into my head. I love to make lists of random stuff. I love to make lists of random words. I even love to make lists of random words that I think of randomly. I often think of random stuff when I'm in the shower. I often think of random stuff when I'm thinking about random stuff.`,
	`The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place.`,
	`The wave roared towards them with speed and violence they had not anticipated. They both turned to run but by that time it was too late. The wave crashed into their legs sweeping both of them off of their feet.`,
	`El otro día quería un perrito caliente, miré en la nevera y no había más salchichas, así que tuve que ir a la tienda de comestibles para conseguir algunas, entonces me di cuenta de que está como a 45 minutos a pie de mi casa, y como no tengo carnet de conducir todavía tuve que dar el largo paseo hasta la tienda, lo vi con optimismo como una forma de hacer algo de ejercicio.`
]
export const excludedKeys = [
	'Shift',
	'Alt',
	'Control',
	'Meta',
	'ArrowUp',
	'ArrowDown',
	'ArrowLeft',
	'ArrowRight',
	'Tab',
	'Backspace',
	'Enter',
	'Escape',
	'Delete',
	'CapsLock',
	'Dead',
	'Home',
	'End',
	'PageUp',
	'PageDown',
	'Insert',
	'F1',
	'F2',
	'F3',
	'F4',
	'F5',
	'F6',
	'F7',
	'F8',
	'F9',
	'F10',
	'F11',
	'F12',
	'NumLock',
	'ScrollLock',
	'Pause',
	'ContextMenu',
	'PrintScreen',
	'OS',
	'Win',
	'Apps',
	'Select',
	'Separator',
	'Clear',
	'Help',
	'NumPad0',
	'NumPad1',
	'NumPad2',
	'NumPad3',
	'NumPad4',
	'NumPad5',
	'NumPad6',
	'NumPad7',
	'NumPad8',
	'NumPad9',
	'Multiply',
	'Add',
	'Subtract',
	'Decimal',
	'Divide',
	'Equal',
	'BracketLeft',
	'BracketRight',
	'Backquote',
	'IntlBackslash',
	'IntlRo',
	'IntlYen',
	'NumpadEqual',
	'NumpadComma',
	'NumpadParenLeft',
	'NumpadParenRight',
	'NumpadBackspace',
	'NumpadClear',
	'NumpadClearEntry',
	'NumpadMemoryStore',
	'NumpadMemoryRecall',
	'NumpadMemoryClear',
	'NumpadMemoryAdd',
	'NumpadMemorySubtract',
	'NumpadSignChange',
	'NumpadClear',
	'NumpadClearEntry',
	'NumpadBinary',
	'NumpadOctal',
	'NumpadDecimal',
	'NumpadHexadecimal',
	'AltGraph',
	'Fn',
	'FnLock'
]
export const charThreshold = 80
export const gradeColors = ['var(--correct)', 'var(--brand-c)', 'var(--warn)']
